# Application Properties
spring:
  application:
    name: Liquibase POC
  # Jpa Properties
  datasource:
    url: jdbc:mysql://localhost:3306/lqpoc
    username: root
    password: Chandu!1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  # Liquibase properties
  liquibase:
    enabled: true
    change-log: /db/db.changelog-dev.xml

